site_name: 'Documentación Interna - Sistemas'
site_description: 'Base de conocimiento y runbooks para el área de sistemas'
repo_name: 'TU-ORG/docs-infra'
nav:
  - Home: index.md
  - IBM:
      - Índice: ibm/index.md
      - Backup y Cambio de Cinta: ibm/backup_cambio_cinta.md
      - Verifiacar Estado de Servidores: ibm/ordenar_trabajos_cpu.md
  - Speed:
      - Índice: speed/index.md
      - Vinculación de guías: speed/vinculacion_guias.md
      - Cambio de moneda en OC: speed/cambio_moneda_oc.md
  - Soporte:
      - Índice: soporte/index.md
      - Instalación de programas: soporte/instalacion_programas.md
      - Instalación de impresoras: soporte/guia_instalacion_impresoras.md
      - Gestionar reglas de correo en Exchange: soporte/reglas_exchange.md
  - Odoo:
      - Índice: odoo/index.md
  - Plantillas:
      - Runbook: templates_docs/runbook_template.md
  - Contenido Protegido: contenido_protegido.md
theme:
  name: material
plugins:
  - search
  - glightbox
  - include-markdown
  - encryptcontent:
      password_inventory:
        secret: "TuContraseñaSegura"
      placeholder: "Contenido protegido. Ingresa la contraseña para acceder."